# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#setting-up-a-cooldown-period-for-dependency-updates

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups: # 1 PR per week and group
      cargo-major:
        update-types: ["major"]
      cargo-minor:
        update-types: ["minor"]
      cargo-patch:
        update-types: ["patch"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups: # 1 PR per week for all images
      actions:
        patterns: ["*"]
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    groups: # 1 PR per week for all submodules
      submodules:
        patterns: ["*"]
