# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "BSD-3-Clause",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MPL-2.0",
    "Unlicense",
    "Zlib"
]
copyleft = "deny"
default = "deny"
confidence-threshold = 0.95
private = { ignore = true }

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"

[bans]
multiple-versions = "allow"