version = "Two"
wrap_comments = true
format_strings = true
format_code_in_doc_comments = true
edition = "2018"
imports_granularity="Crate"
imports_layout = "HorizontalVertical"
reorder_imports = true
