name: Third-party licences

permissions: write-all

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  allowed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # pull the fork's HEAD instead of the main repo's
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Assert Glommio depends on crates permissively licensed
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          log-level: warn
          command: check licenses
          arguments: --all-features

  comment:
    runs-on: ubuntu-latest

    needs: [ allowed ]
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # pull the fork's HEAD instead of the main repo's
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Render Template
        id: template
        uses: chuhlomin/render-template@v1.2
        with:
          template: .github/templates/license_check_failed.md
          vars: |
            user: ${{ github.event.pull_request.user.login }}

      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.template.outputs.result }}
