name: Third-party vulnerabilities

permissions: write-all

on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Run checks on third-party dependencies
        uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 # v2.0.15
        with:
          log-level: warn
          command: check
          arguments: --all-features
